

services:
  backend:
    build: ./backend
    container_name: backend_app
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    networks:
      - backend_network
    command: ["uvicorn", "__init__:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


  redis:
    image: "redis:latest"
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network

  mongo:
    image: "mongo:latest"
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend_network
    volumes:
      - mongo_data:/data/db

  celery:
    build: ./backend
    container_name: celery_worker
    command: ["celery", "-A", "celery_tasks.celery", "worker", "--loglevel=info"]
    depends_on:
      - backend
      - redis
    networks:
      - backend_network

volumes:
  mongo_data:

networks:
  backend_network:
    driver: bridge
