# Use official Python image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy the backend code
COPY . /app

# Copy dependencies and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Expose FastAPI port
EXPOSE 8000

# Start FastAPI app
CMD ["uvicorn", "__init__:app", "--host", "0.0.0.0", "--port", "8000"]
